### ISSUE TITLE
Targeted fps mode? ffv1 (archival) mode codec support, or pro res xq (ffmpeg)?

### ISSUE THREAD

**Issue by zelenooki87** [JHLew/MoMo#1]
Hi, thank you for wonderfull project.
This is the best frame interpolation method I have ever seen.
I have not realized how to run targeted fps instead of 2x(by default) framerate interpolation. Is there a such option?
Could you modify code to support ffv1(looosless) codecs, or prores xq, hq? and output video to keep audio (or convert it to aac 320kbps)
Thank you very much in advance :)

**Comment by profile838** [comment]
In meantime I created script for batch input support.
You need ffmpeg installed.
FFV1 is default format, you can change it. 
original audio supported
script located here:
https://pastebin.com/fhyccLeT
example of usage:
accelerate launch batch.py --input_dir input --output_dir output --mp bf16

**Comment by JHLew** [comment]
Thank you for your interest in our work.

- Our project is designed for 2x frame interpolation, and currently there is no explicit option to set a target fps rate. In case you want to interpolate to a certain fps, you can choose to run our model recurrently depending on the input video fps and output video fps. (e.g., 30fps input video -> 240fps target video: run our model recurrently 3 times; 30fps -> 60fps -> 120fps -> 240fps)

- As far as I know, the `demo.py` will be able to process a large variety of video codecs, based on the `VideoCapture` class from opencv.

- Our project is mainly focused on video frames, so the codes in this project do not handle audios at the moment. I could try adding the option for audio preserving, but since I am not familiar with handling audios, it could take a while.

- While writing this reply, I found that you have implemented the functions you requested. Thank you for your effort :)
