### ISSUE TITLE
fp16 support? (Single GPU)

### ISSUE THREAD

**Issue by zelenooki87** [JHLew/MoMo#2]
Cant figure why fp16 no supported by default by entering arguments:
accelerate launch .....    --mp fp16
I am getting warning.

```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
```

I am getting 15-20fps with RTX 3090 24GB,64GB RAM, Ryzen 7950x.
Is code limitted to full precision on single gpu or no?
It would be realy nice to speed up inference.
Thanks

**Comment by profile838** [comment]
My appologize, fp16 really speed up inference. At least on Ubuntu machine. On windows cant get better speeds.
But in my case, output video flickering with fp16 argument.
With bf16 inference runs at same speed as fp16 but output video is as expected.
Could you tell me does mixed precission argument affects in some way to video interpolation quality?

Thanks :)

**Comment by JHLew** [comment]
Mixed precision is disabled by default in our project, because it did not lead to much speed up (at least in my environment), and the generated intermediate motions sometimes contained NaN values with fp16. I could not test with bf16 as my environment did not support it.
So I guess fp16 could lead to bad results, which I suspect is due to extremely small values exceeding the representational range, and therefore inference with bf16 or without mixed precision would be recommendable.
